openapi: 3.0.0

info:
 version: '0.1'
 title: 'Gamma Public API'
 description: 'Web Resources Specification (A7) for Gamma'

servers:
- url: htts://lbaw2391.lbaw.fe.up.pt
  description: Production server

externalDocs:
 description: Find more info here.
 url: https://git.fe.up.pt/lbaw/lbaw2324/lbaw2391/-/wikis/eap

tags:
 - name: 'M01: Authentication'
 - name: 'M02: Feed'
 - name: 'M03: User Admnistration'
 - name: 'M04: Static Pages'
 - name: 'M04: User Profile'
 - name: 'M05: Search'
 - name: 'M06: Posts'
 - name: 'M07: Groups'

paths:

  /login:

    get:
      operationId: R101
      summary: 'R101: Login Form'
      description: 'Provide login form. Access: VST'
      tags:
        - 'M01: Authentication'

      responses:
        '200':
          description: 'Get login form view.'

    post:
      operationId: R102
      summary: 'R102: Login Action'
      description: 'Processes the login form submission. Access: VST'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/x-www-form-urllencoded:
            schema:
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                  - email
                  - password

      responses:
        '302':
          description: 'Redirect after processing the new user information.'
          headers:
            Location:
              schema:
                type: string
              examples:
                '302 Success':
                  description: 'OK. Redirect to homepage.'
                  value: '/home'
                '302 Failure':
                  description: 'NOT OK. Redirect again to login form.'
                  value: '/login'
            Set-Cookie:
              cookie-name: 
                type: string
              cookie-value:
                type: string
              Expires:
                type: string

  /logout:

    post:
      operationId: R103
      summary: 'R103 : Logout Action'
      description: 'Logout the current logged user. Access: USR, ADM'
      tags:
        - 'M01: Authentication'

      responses:
        '302':
          description: 'Redirect after processing logout.'
          headers:
            Location:
              schema:
                type: string
              examples:
                '302 Success':
                  description: 'OK. Redirect to public feed.'
                  value: '/'

  /register:

      get:
        operationId: R104
        summary: 'R104: Register Form'
        description: 'Register a new user. Access: VST'
        tags:
          - 'M01: Authentication'

        responses:
          '200':
            description: 'Sign-up is ready'
      
      post:
        operationId: R105
        summary: 'R105: Register Action'
        description: 'Processes a new registration request. Access: VST'
        tags:
          - 'M01: Authentication'
        
        requestBody:
          required: true
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  image:
                    type: text
                    format: binary
                  username:
                    type: string
                  email:
                    type: string
                  academic_status:
                    type: string
                  display_name:
                    type: string
                  is_private:
                    type: boolean
                required:
                      - email
                      - password
                      - username
          
        responses:
          '302': 
            description: 'Redirect after the register'
          headers:
            Location:
              schema:
                type: string
              examples:
                '302 Success':
                  description: 'The user was registered with success. Redirect to his personal page'
                  value: '/users/{id}'
                '302 Failure':
                  description: 'The user was not registered with success. Redirect to the login form'
                  value: '/login'

  api/sendResetPassword:

    post:
      operationId: R106
      summary: 'R106 : Send Email Action'
      description: 'Sends an email with a certain type. Access: VST'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                e-mail:
                  type: string
              required:
                - email
               
      responses:
        '200':
          description: 'OK. An e-mail with a password link was sent.'

  /resetPassword/{token}:

    get:
      operationId: R107
      summary: 'R107: Register Form'
      description: 'Get the view for the form to reset the password. Access: VST'
      tags:
        - 'M01: Authentication'

      responses:
        '200':
          description: 'Reset the password form returned'

    post:
      operationId: R108
      summary: 'R108 : Reset Password'
      description: 'Sends a reset password request. Access: VST'
      tags:
        - 'M01: Authentication'

      parameters:
        - in: path
          name: token
          schema:
            type: string
          required: True

      requestBody:
        required: True
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                new_passsword:
                  type: string
                confirm_new_password:
                  type: string
              required:
                - new_password
                - confirm_new_password
               
      responses:
        '200':
          description: 'OK. You received a token on your email.'
        '404':
          description: 'Error. Email doesnt exists.'


  api/sendVerifyEmail:

    post:
      operationId: R108
      summary: 'R108 : Send Email Action'
      description: 'Sends an email with a certain type. Access: VST'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                e-mail:
                  type: string
              required:
                - email
                
      responses:
        '200':
          description: 'OK. You received a token on your email.'
        '404':
          description: 'Error. Email doesnt exists.'

  /verifyEmail/{token}:

    get:
      operationId: R109
      summary: 'R109: Verify Email Form'
      description: 'Get the view for the form to reset the password. Access: VST'
      tags:
        - 'M01: Authentication'

      responses:
        '200':
          description: 'Reset the verify email form returned'

    post:
      operationId: R110
      summary: 'R110 : Send Verify Email Request'
      description: 'Sends a verify email request to the server'
      tags:
        - 'M01: Authentication'

      responses:
        '200':
          description: 'OK. Email verified.'

  /feed/{type}:

      get:
        operationId: R301
        summary: 'R301: Provide feed form'
        description: 'Get the page with the feed. Access: USR, ADM'
        tags:
          - 'M03: Feed'

        responses:
          '200':
            description: 'OK. Show feed UI'

  /users/{username}:

      get:
        operationId: R501
        summary: 'R501 : Profile Action'
        description: 'Get the page view for a user profile'
        tags:
          - 'M05: Profile'

        responses:
          '200':
            description: 'OK. Show User Profile'
          '403':
            description: 'Forbidden. User doesn't have access to this profile.'

  /users/{id}/edit:

      get:
        operationId: R502
        summary: 'R502 : Edit Profile Form.'
        description: 'Provide edit profile form. Access: ATH'
        tags:
          - 'M05: Profile'

        responses:
          '200':
            description: 'Get the view of the edit post form'
          '403':
            description: 'Forbidden. User doesn't own this profile.'

      put:
        operationId: R503
        summary: 'R503 : Edit Profile Action.'
        description: 'Processes the edit profile form submission. Access: ATH'
        tags:
          - 'M05: Profile'
        
        requestBody:
          required: true
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  image:
                    type: text
                    format: binary
                  username:
                    type: string
                  academic_status:
                    type: string
                  display_name:
                    type: string
                  is_private:
                    type: boolean
                required:
        
        responses:
          '302':
            description: 'Redirect after processing the new user information.'
            headers:
              Location:
                schema:
                  type: string
                examples:
                  '302 Success':
                    description: 'OK. Redirect to profile page.'
                    value: '/users/{id}'
                  '302 Failure':
                    description: 'NOT OK. Redirect again to edit profile form.'
                    value: '/users/{id}/edit'

  /post:

    post:
      operationId: R601
      summary: 'R601 : Create Post Action'
      description: 'Processes the create post form submission. Access: ATH'
      tags:
        - 'M06: Posts'
      
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                attachment:
                  type: text
                  format: binary
                title:
                  type: string
                content:
                  type: string
                is_private:
                  type: boolean
                group:
                  type: string
              required:
                - title
                - content
                - is_private

      responses:
        '302':
          description: 'Redirect after processing the new post information.'
          headers:
            Location:
              schema:
                type: string
              examples:
                '302 Success':
                  description: 'OK. Redirect to post page.'
                  value: '/post/{id}'
                '302 Failure':
                  description: 'NOT OK. Redirect again to create post form.'
                  value: '/post'

  /api/post/{id}:
    get: 
      operationId: R602
      summary: 'R602: Get post from id as JSON'
        description: 'Get post from id. Access: ATH'
        tags:
          - 'M06: Posts'

        responses:
          '200':
            description: 'OK.'
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                 properties:
                   author:
                    type: string
                   title:
                     type: string
                   content:
                     type: string
                   date:
                     type: string
                   attachment:
                     type: string
                   group:
                     type: string
               example:
                 - author: killme
                   title: MongoDB vs ScyllaDB 
                   content: Can you provide with explanation as to which one of those are better?
                   date: 2023-10-29,
                   attachment: null,
                   group: null
          '403':
            description: 'Forbidden. User doesn't own this post.' 

                
  /post/{id}:

    get: 
      operationId: R603
      summary: 'R603: Edit Profile Form.'
        description: 'Provide edit profile form. Access: ATH'
        tags:
          - 'M06: Posts'

        responses:
          '200':
            description: 'OK. Show Post'
          '403':
            description: 'Forbidden. User doesn't own this post.' 

    put:
      operationId: R604
      summary: 'R604: Edit Post Action'
      description: 'Processes the edit post form submission. Access: ATH'
      tags:
        - 'M06: Posts'
      
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                attachment:
                  type: text
                  format: binary
                title:
                  type: string
                content:
                  type: string
                is_private:
                  type: boolean
                required:

  delete:
    operationId: R605
    summary: 'R605: Delete Post Action'
    description: 'Processes the delete post form submission. Access: ATH'
    tags:
      - 'M06: Posts'

    responses:
      '302':
        description: 'Redirect after processing the delete post information.'
        headers:
          Location:
            schema:
              type: string
              examples:
                '302 Success':
                  description: 'OK. Redirect to feed.'
                  value: '/feed'
                '302 Failure':
                  description: 'NOT OK. Redirect again to post page.'
                  value: '/post/{id}'

  /search/{query}:

    get: 
      operationId: R606
        summary: 'R606: Users Search Action'
        description: 'Allows the search for users'
        tags:
          - 'M06: Posts'
        
        responses:
          '200':
            description: 'OK. Show Search Users UI'
    
  /api/search/users:

    get:
      operationId: R504
        summary: 'R504: Previews the users search result to use for AJAX'
        description: 'Allows the search for users'
        tags:
          - 'M05: Search'
      
      parameters:
      - in: query
        name: query
        description: String to use for full-text search
        schema:
          type: string
        required: false
      
        
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    image:
                      type: string
                    username:
                      type: string
                    e-mail:
                      type: string
                    academic_status:
                      type: string
                    display_name:
                      type: string
                    is_private:
                      type: boolean
                example:
                  - id: 1
                    image: url/of/the/image.jpg
                    username: john_doe
                    e-mail: johndoe@trigger.com
                    academic_status: Student 
                    display_name: John Doe
                    is_private: False
                  - id: 28
                    image: url/of/the/image2.jpg
                    username: carlosbarbossa
                    e-mail: carlosbarbossa@carlosbarbossa.com
                    academic_status: Student 
                    display_name: Carlos Barbossa
                    is_private: False

  /api/search/posts:

    get: 
      operationId: R505
        summary: 'R505: Posts Search Action'
        description: 'Allows the search for posts'
        tags:
          - 'M05: Search'
          
        parameters:
        - in: query
          name: query
          description: String to use for full-text search
          schema:
            type: string
          required: false
      

        responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    author:
                      type: integer
                    title:
                      type: string
                    content:
                      type: string
                    attachement:
                      type: string
                    group_id:
                      type: integer
                    is_private:
                      type: boolean

  /api/search/groups:

    get:
      operationId: R701
        summary: 'R702: Previews the groups search result to use for AJAX'
        description: 'Allows the search for groups'
        tags:
          - 'M07: Groups'
      
      parameters:
      - in: query
        name: query
        description: String to use for full-text search
        schema:
          type: string
        required: false
      
        
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    is_private:
                      type: boolean
                example:
                  - id: 1
                    name: Prolog Enthusiasts
                    description: A community for discussing Prolog programming language and related topics
                    is_private: False
                  - id: 2
                    name: Tech Enthusiasts
                    description: A group dedicated to discussing the latest technology trends and innovations
                    is_private: True
